### PR TITLE
V0.3.4

### PR DESCRIPTION
**Pull request by gjohansson-ST**
- Correct function for panic button
 - Modify the usage of backoff component
 - Implement full exception handling
 - functions.md for full overview

### CODE REVIEW

**Comment by gjohansson-ST** [comment]
@domwillcode can you push to pypi after merge?

**Comment by domwillcode** [comment]
No problem, I'll sort it tomorrow. Nice work with all of this! I have a lot to catch up on 😳
PM your pypi username and I'll get you added to the package.

**Comment by gjohansson-ST** [comment]
> No problem, I'll sort it tomorrow. Nice work with all of this! I have a lot to catch up on 😳
> PM your pypi username and I'll get you added to the package.

Can you do DM on github?
Anyway my username on pypi is gjohansson

**Comment by domwillcode** [comment]
> Can you do DM on github?

I guess not :) Added you.

And: https://pypi.org/project/yalesmartalarmclient/0.3.4/

**Pull request merged**
