### PR TITLE
PR for fetching the url from services endpoint

### PR DESCRIPTION
**Pull request by p-tech-se**

### CODE REVIEW

**Comment by p-tech-se** [comment]
@laf 
The doorman function is for the Doorman locks, will remember to separate the PR's in the future :)
I only have the doorman lock connected but I assume you get status for every device connected.

**Comment by laf** [comment]
> I only have the doorman lock connected but I assume you get status for every device connected.

Yes you do which could provide for some interesting integrations into HASS for things like PIR sensors and the like.

**Comment by domwillcode** [comment]
Great work! I'm currently working away but I'll give this a test tomorrow.

**Comment by charlesastaylor** [comment]
Hi, maybe not the best to reuse pythons built in `list` as a variable name in `get_locks_status`?

**Comment by charlesastaylor** [comment]
Hi, maybe not the best to reuse pythons built in `list` as a variable name in `get_locks_status`?

**Comment by p-tech-se** [comment]
True, I have renamed list to locks.

**Comment by laf** [comment]
@p-tech-se Would you mind rebasing this?

**Comment by p-tech-se** [comment]
Sure, I don’t have time right now but I will do it during the weekend.

**Comment by laf** [comment]
Thanks @p-tech-se

**Comment by laf** [comment]
Looks good to me, the only exception is you've changed the file permissions on both the files you've changed from 0644 to 0755, you should revert them to 0644.

**Comment by p-tech-se** [comment]
@laf 
Sorry about that, I have reverted it 0644

**Comment by domwillcode** [comment]
@laf, that would be amazing if you get chance, free time is few and far between at the mo. Otherwise I'll probably get chance tomorrow.

**Pull request merged**
