### PR TITLE
Cosmetic and code-style cleanup

### PR DESCRIPTION
**Pull request by espenfjo**
I did a small, perhaps cosmetic, cleanup of most of the code.

### CODE REVIEW

**Comment by gjohansson-ST** [comment]
Cool. Haven't noticed this one until now. I will have a look at it.

**Comment by domwillcode** [comment]
I'd managed to miss it too, thanks for the nudge. It looks good to me but welcome a second pair of eyes (Python is not my first language as you can probably tell ;) ).

**Review by gjohansson-ST — APPROVED** [review]
Nice work

**Comment by gjohansson-ST** [comment]
@domwillcode updated the rep to 0.3.5
You want to publish a new package?

**Comment by domwillcode** [comment]
Took my sweet time, but it's here: 
https://pypi.org/manage/project/yalesmartalarmclient/release/0.3.5/

Thanks for the contributions chaps!

**Pull request merged**
