### PR TITLE
#28: Fix for yapi/yapi after adding the panic button

### PR DESCRIPTION
**Pull request by diazwatson**
This PR should fix the issue discovered by @Mr-Grover  in https://github.com/domwillcode/yale-smart-alarm-client/issues/28

### CODE REVIEW

**Review by Mr-Grover — COMMENTED** [review]
Now I am seeing (requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://mob.yalehomesystem.co.uk/api/panel/device_status/) when trying to unlock the lock and or unlock the lock.

**Comment by diazwatson** [comment]
The other option I see is the other way around.
Basically, add back the `yapi` bit to the URL (as it was originally) and only remove it when the panic button endpoint is called 🤔

**Comment by Mr-Grover** [comment]
Whatever you want to try I should be able to test. I have all the hardware this api covers.

**Comment by diazwatson** [comment]
I have updated my PR with this new approach.
Triggering the alarm from HA works as expected.

But I get this in my console:
```
2021-05-13 16:30:02 INFO (SyncWorker_2) [homeassistant.loader] Loaded lock from homeassistant.components.lock
2021-05-13 16:30:02 INFO (MainThread) [homeassistant.setup] Setting up lock
2021-05-13 16:30:02 INFO (MainThread) [homeassistant.setup] Setup of domain lock took 0.0 seconds
2021-05-13 16:30:02 INFO (MainThread) [homeassistant.components.lock] Setting up lock.yale_smart_sync
2021-05-13 16:30:02 ERROR (MainThread) [homeassistant.components.lock] Error while setting up yale_smart_sync platform for lock
Traceback (most recent call last):
  File "/homeassistant/homeassistant/helpers/entity_platform.py", line 243, in _async_setup_platform
    await asyncio.shield(task)
  File "/homeassistant/homeassistant/components/yale_smart_sync/lock.py", line 28, in async_setup_entry
    pin = config_entry.data[CONF_PIN]
KeyError: 'pin'
2021-05-13 16:30:02 INFO (MainThread) [homeassistant.bootstrap] Home Assistant initialized in 3.93s
2021-05-13 16:30:02 INFO (MainThread) [homeassistant.core] Starting Home Assistant
2021-05-13 16:30:02 INFO (MainThread) [homeassistant.core] Timer:starting
2021-05-13 16:30:02 INFO (SyncWorker_1) [homeassistant.components.zeroconf] Starting Zeroconf broadcast
2021-05-13 16:30:02 INFO (MainThread) [homeassistant.components.automation.test_alarm] Initialized trigger Test Alarm
```

**Comment by Mr-Grover** [comment]
I need to default the pin to 0000 I am guessing you never entered a pin code when setting up the platform. I will give your code a test in a bit

**Comment by Mr-Grover** [comment]
@diazwatson Just finished testing and everything seems to work. My lock is able to lock and unlock and the status change is working for the door contacts as well.

Great job

**Comment by diazwatson** [comment]
Any idea what is that error all about?

**Comment by Mr-Grover** [comment]
> Any idea what is that error all about?

I spoke to the error already. Also you might want to check the home assistant forum. I tagged you in a post. Someone else has already rewrote the Yale app and has a pr in place. They didn’t add the alarm though so hopefully they can

**Comment by domwillcode** [comment]
Seems we're covered by #30 now. Happy to close this off?

**Comment by Mr-Grover** [comment]
Yeah I think that makes sense. We will continue to test and submit PRs if needed. 

Thanks for looking at this :)

**Comment by diazwatson** [comment]
Guys, I think these changes are still needed as they remove the duplication of the `yapi/yapi` in the Url and allows the use of the panic button.

Could you please test these changes and let me know if they break any of your integration?
@Mr-Grover  @gjohansson-ST @domwillcode

**Comment by gjohansson-ST** [comment]
> Guys, I think these changes are still needed as they remove the duplication of the `yapi/yapi` in the Url and allows the use of the panic button.
> 
> Could you please test these changes and let me know if they break any of your integration?
> @Mr-Grover @gjohansson-ST @domwillcode

I will look at it later today

**Pull request merged**
